# Generated by Django 4.2 on 2023-04-25 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoCurrency', '0002_remove_cryptocurrencyhistory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrencyhistory',
            old_name='currency',
            new_name='currency_name',
        ),
    ]
